services:
  mqtt:
    container_name: mqtt
    image: eclipse-mosquitto:2
    restart: unless-stopped
    volumes:
      - ./mosquitto/config:/mosquitto/config
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log
    ports:
      - 1883:1883

  zigbee2mqtt:
    container_name: zigbee2mqtt
    image: ghcr.io/koenkk/zigbee2mqtt
    restart: unless-stopped
    volumes:
      - ./z2m-data:/app/data
      - /run/udev:/run/udev:ro
    ports:
      - 8099:8080
    environment:
      - TZ=America/New_York
    devices:
      - /dev/serial/by-id/usb-ITead_Sonoff_Zigbee_3.0_USB_Dongle_Plus_6ebfed430d6bef11b662a4adc169b110-if00-port0:/dev/ttyACM0
    depends_on:
      - mqtt

  server:
    container_name: minhome-server
    build:
      context: .
      dockerfile: server/Dockerfile
    restart: unless-stopped
    ports:
      - 3111:3111
    volumes:
      - ./config.json:/app/config.json
      - ./automations.json:/app/automations.json
    environment:
      - MQTT_URL=mqtt://mqtt:1883
      - DATA_DIR=/app
    depends_on:
      - mqtt
